### ISSUE TITLE
Does this package support to load 16-bit image?

### ISSUE THREAD

**Issue by Yuvi-416** [conda-forge/openimageio-feedstock#47]
I was trying to load an array of the 16-bit image using this package but I am getting an error as:
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. OpenImageIO.ImageBuf()
    2. OpenImageIO.ImageBuf(arg0: str)
    3. OpenImageIO.ImageBuf(arg0: str, arg1: int, arg2: int)
    4. OpenImageIO.ImageBuf(arg0: OpenImageIO.ImageSpec)
    5. OpenImageIO.ImageBuf(arg0: OpenImageIO.ImageSpec, arg1: bool)
    6. OpenImageIO.ImageBuf(name: str, subimage: int, miplevel: int, config: OpenImageIO.ImageSpec)
   
I understood the error, but I didn't understand how can I pass the array using this library. If it can pass then can I do something like the below which I did for an 8-bit image using PIL library:

```
img_tiles_org = Image.fromarray(bf_tiles_org).convert("RGB")
instance_byte_str_buffer_org = BytesIO()
img_tiles_org.save(instance_byte_str_buffer_org, "JPEG", quality=80, icc_profile=img_tiles_org.info.get('icc_profile'), progressive=False)
t_org = instance_byte_str_buffer_org.getvalue()
```
Before I was using Pillow library to save image bytes in jpeg compression for the 8-bit image but now I have a 16-bit image therefore, I can't use the PIL library anymore.
I also tried OpenCV-python but it has a limitation, it can't save a jpeg image of 16-bit as I understood.
Therefore, I would like to know if there is any library or package which can help me to load the bytes of an image and its ICC profile too.
I really need some suggestion regarding it.
Thank you

**Comment by wolfv** [comment]
Hey, I think it will be better if you ask upstream
