### ISSUE TITLE
The feedstock has no Python support.

### ISSUE THREAD

**Issue by KelSolaar** [conda-forge/openimageio-feedstock#6]
Issue:

I tried the feedstock but importing `OpenImageIO` fails which seems logical given the library is seemingly built without Python support: https://github.com/conda-forge/openimageio-feedstock/blob/master/recipe/build.sh#L11:

```bash
(oiio-ci) Kali:~ kelsolaar$ python -c "import OpenImageIO;print(OpenImageIO.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'OpenImageIO'
```

$ conda list

```
(oiio-ci) Kali:~ kelsolaar$ conda list
# packages in environment at /usr/local/anaconda3/envs/oiio-ci:
#
# Name                    Version                   Build  Channel
boost                     1.69.0          py37h9888f84_1001    conda-forge
boost-cpp                 1.69.0            h6f8c590_1000    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
ffmpeg                    3.4.2                hf82bc7d_2    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
gnutls                    3.6.5             h53004b3_1002    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
ilmbase                   2.3.0             hd9629dc_1001    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcxx                    8.0.1                         0    conda-forge
libcxxabi                 8.0.1                         0    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h4bb4525_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libwebp                   1.0.2                h14d73da_2    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
nettle                    3.4.1             h3efe00b_1002    conda-forge
numpy                     1.17.2           py37h6b0580a_0    conda-forge
openexr                   2.3.0             h5c9b4e4_1000    conda-forge
openimageio               1.8.17               h801958d_2    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
pip                       19.2.3                   py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                41.2.0                   py37_0    conda-forge
sqlite                    3.29.0               hb7d70f7_1    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
x264                      1!152.20180806       h1de35cc_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h01d97ff_1006    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```
$ conda info

```
(oiio-ci) Kali:~ kelsolaar$ conda info

     active environment : oiio-ci
    active env location : /usr/local/anaconda3/envs/oiio-ci
            shell level : 1
       user config file : /Users/kelsolaar/.condarc
 populated config files : /Users/kelsolaar/.condarc
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /usr/local/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /Users/kelsolaar/.conda/pkgs
       envs directories : /usr/local/anaconda3/envs
                          /Users/kelsolaar/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by KelSolaar** [comment]
I was about to try the [QuantStack Conda package](https://anaconda.org/QuantStack/openimageio/) but I just realised that @SylvainCorlay who contributed to this feedstock is actually from QuantStack, so I'm assuming the same issue is present there.

**Comment by wolfv** [comment]
Hi @KelSolaar 

indeed it says "WITH_PYTHON=OFF" in the build script.

The question is wether the package should come with Python bindings by default, or wether a seperate package with the python bindings should be distributed ... I will ask on the conda-forge gitter channel.

**Comment by KelSolaar** [comment]
@wolfv : Cheers! I would use it for my various packages if it was available, even for CI purposes, right now I'm building it which is quite long.

**Comment by wolfv** [comment]
Hi @KelSolaar seems like we need to add an outputs section: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section

Do you want to help with that?

**Comment by KelSolaar** [comment]
I don't really have much experience with building Conda packages, I guess my first question would be how various Python versions are being handled?

**Comment by wolfv** [comment]
@KelSolaar various python versions are handled automatically once you start depending on Python, it creates 3 builds for py 3.5, 3.7, and 3.8.

The GDAL feedstock is doing some tricks as well to get multiple outputs https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/meta.yaml

**Comment by lgritz** [comment]
Poking this issue -- I'm the main author of the upstream package, but am a total noob with Conda. 

The conda distro of this package seems to be intentionally disabling the python bindings, as well as the command line utilities (which are a really important component of what people think they will get when they install this package).

How can we make progress toward getting those two things re-enabled in the conda distribution of OpenImageIO?

**Comment by wolfv** [comment]
Hi @lgritz! 

We have enabled the python library as a seperate output now! You can find it under py-openimageio :)

https://github.com/conda-forge/openimageio-feedstock/blob/master/recipe/meta.yaml

Let me know if it works for you, it should be already available on conda-forge (`conda install -c conda-forge py-openimageio`)

**Comment by lgritz** [comment]
Thanks so much for the immediate response, @wolfv !

I have relayed this to the user who was having trouble, and I'm hopeful it will solve his problem, assuming that the only component he was missing was the python module.

Is there also a way for somebody to get the command line utilities? Or any particular reason they should remain disabled?

**Comment by wolfv** [comment]
Do you want to make a PR to this repo? I’m happy to merge it (also you can add yourself as a maintainer in the meta.yaml file).

**Comment by lgritz** [comment]
I'm happy to fix that, as well as to occasionally bump the version it pulls as we make new releases.

But like I said, I'm a total Conda amateur, so I'm not very confident about how I'd test it on my end prior to merge.

**Comment by wolfv** [comment]
IMO the way to get started is to 

1. install miniconda (https://docs.conda.io/en/latest/miniconda.html)
2. configure the conda-forge channel (using

```
conda config --add channels conda-forge 
conda config --set channel_priority strict 
```

3. installing conda-build with `conda install conda-build`
4. run conda build in the recipe folder `conda build ..../openimageio-feedstock/recipe/`

This will build a local copy of openimageio and py-openimageio (you can install it using `conda install -c local openimageio`.
The build output will go to `~/miniconda3/conda-bld/{linux-64|osx-64|win-64}/openimageio-....tar.bz2`

This might help to get you started :)

**Comment by wolfv** [comment]
I'll close this issue for the moment because, as outlined above, we do have python support now :)
